#!groovy

pipeline {
    agent any
    options {
        skipDefaultCheckout()
    }

    stages {        
        stage('Build') {
            steps {
                echo 'Building.. Web App'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}